# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['src\\main.py',
              'src\\allocate.py',
              'src\\nearest.py',
              'src\\build_graph.py',
              'src\\person.py',
              'src\\facility.py',
              'src\\Core\\common.py',
              'src\\Core\\core.py',
              'src\\Core\\DataFactory.py',
              'src\\Core\\fgdb.py',
              'src\\Core\\filegdbapi.py',
              'src\\Core\\graph.py',
              'src\\Core\\log4p.py',
              'src\\Core\\simplification.py',
              'src\\Core\\utils_graph.py',
              'src\\Core\\check.py',
              'src\\Core\\ogrmerge.py'],
             pathex=['D:\\空间模拟\\mNA'],
             binaries=[('D:\GDAL370\\bin\\gdal\\plugins-package', 'Library\\lib\\gdalplugins'),
                       ('D:\\GDAL370\\bin\\FileGDBAPI.dll', '.'),
                       ('.\\src\\Core\\_filegdbapi.pyd', 'Core')],
             datas=[('.\\qgis\\Library\\share\\proj', 'Library\\share\\proj')],
             hiddenimports=['osgeo', 'filegdbapi'],
             hookspath=[],
             runtime_hooks=['hook.py'],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
          cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          exclude_binaries=False,
          name='mNA',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          icon=".\\icons\\logo.ico",
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          version="version_main.py")
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               upx_exclude=[],
               debug=True,
               console=True,
               name='mNA')
